spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: news-service
          uri: lb://news-service:8083
          predicates:
            - Path=/news/**
        - id: user-service
          uri: lb://user-service:8081
          predicates:
            - Path=/users/**
        - id: rate-service
          uri: lb://rate-service:8084
          predicates:
            - Path=/rate/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/trading-platform
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true